# Generated by Django 5.2.10 on 2026-02-11 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_aidiagnosis_prediction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aidiagnosis',
            name='severity_level',
            field=models.CharField(max_length=20),
        ),
    ]
